name: 'Check PR Lint'
description: 'Automatically check branch validation'
inputs:
  branch:
    description: 'Branch name'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.branch }}
